export enum ROUTES {
  auth = 'auth',
  users = 'users',
  team = 'team',
  clients = 'clients',
  projects = 'projects',
  surveys = 'surveys',
  auditors = 'auditors',
  priceMonitoring = 'price-monitoring',
  auditorAuth = 'auditor-auth',
  auditor = 'auditor',
}

export const apiRoutes = {
  auth: {
    register: `${ROUTES.auth}/register`,
    login: `${ROUTES.auth}/login`,
    refresh: `${ROUTES.auth}/refresh`,
    logout: `${ROUTES.auth}/logout`,
  },
  users: {
    me: `${ROUTES.users}/me`,
  },
  team: {
    users: `${ROUTES.team}/users`,
    usersExport: `${ROUTES.team}/users/export`,
    userProjectAccess: (userId: string) => `${ROUTES.team}/users/${userId}/project-access`,
    userPointAccess: (userId: string) => `${ROUTES.team}/users/${userId}/point-access`,
    userResetPassword: (userId: string) => `${ROUTES.team}/users/${userId}/password/reset`,
    groups: `${ROUTES.team}/groups`,
    group: (groupId: string) => `${ROUTES.team}/groups/${groupId}`,
    groupMembers: (groupId: string) => `${ROUTES.team}/groups/${groupId}/members`,
    groupMembersImport: (groupId: string) => `${ROUTES.team}/groups/${groupId}/members/import`,
    groupAddByEmail: (groupId: string) => `${ROUTES.team}/groups/${groupId}/members/add-by-email`,
    userGroups: (userId: string) => `${ROUTES.team}/users/${userId}/groups`,
    userCompaniesAccess: (userId: string) => `${ROUTES.team}/users/${userId}/companies-access`,
    userCompanyDistribution: (userId: string, companyId: string) => `${ROUTES.team}/users/${userId}/distribution/${companyId}`,
    companyFilterValues: (companyId: string) => `${ROUTES.team}/distribution/${companyId}/filter-values`,
    userCompanyReports: (userId: string, companyId: string) => `${ROUTES.team}/users/${userId}/reports/${companyId}`,
    userClone: (userId: string) => `${ROUTES.team}/users/${userId}/clone`,
    bulkProjectAccess: `${ROUTES.team}/users/project-access/bulk`,
    roleDefaultPermissions: `${ROUTES.team}/role-default-permissions`,
  },
  clients: {
    clients: `${ROUTES.clients}`,
    client: (clientId: string) => `${ROUTES.clients}/${clientId}`,
    owners: (clientId: string) => `${ROUTES.clients}/${clientId}/owners`,
    logo: (clientId: string) => `${ROUTES.clients}/${clientId}/logo`,
    background: (clientId: string) => `${ROUTES.clients}/${clientId}/background`,
    apUpload: (clientId: string) => `${ROUTES.clients}/${clientId}/ap/upload`,
    usersImport: (clientId: string) => `${ROUTES.clients}/${clientId}/users/import`,
  },
  projects: {
    projects: `${ROUTES.projects}`,
    project: (projectId: string) => `${ROUTES.projects}/${projectId}`,
    addressbook: (projectId: string) => `${ROUTES.projects}/${projectId}/addressbook`,
    addressbookUpload: (projectId: string) => `${ROUTES.projects}/${projectId}/addressbook/upload`,
    addressbookExport: (projectId: string) => `${ROUTES.projects}/${projectId}/addressbook/export`,
    addressbookPointCreate: (projectId: string) => `${ROUTES.projects}/${projectId}/addressbook/points`,
    addressbookPoint: (projectId: string, pointId: string) => `${ROUTES.projects}/${projectId}/addressbook/points/${pointId}`,
    addressbookClone: (projectId: string) => `${ROUTES.projects}/${projectId}/addressbook/clone`,
    checklists: (projectId: string) => `${ROUTES.projects}/${projectId}/checklists`,
    checklistsExport: (projectId: string) => `${ROUTES.projects}/${projectId}/checklists/export`,
    checklistsUpload: (projectId: string) => `${ROUTES.projects}/${projectId}/checklists/upload`,
    checklistDetails: (projectId: string, checklistId: string) => `${ROUTES.projects}/${projectId}/checklists/${checklistId}`,
    checklistItemsExport: (projectId: string, checklistId: string) => `${ROUTES.projects}/${projectId}/checklists/${checklistId}/items/export`,
    checklistItems: (projectId: string, checklistId: string) => `${ROUTES.projects}/${projectId}/checklists/${checklistId}/items`,
    checklistItem: (projectId: string, checklistId: string, itemId: string) =>
      `${ROUTES.projects}/${projectId}/checklists/${checklistId}/items/${itemId}`,
    pointCatalog: (projectId: string, pointId: string) => `${ROUTES.projects}/${projectId}/points/${pointId}/catalog`,
    refRegions: `${ROUTES.projects}/refs/regions`,
    refCities: `${ROUTES.projects}/refs/cities`,
    projectSurveys: (projectId: string) => `${ROUTES.projects}/${projectId}/surveys`,
    projectSurvey: (projectId: string, surveyId: string) => `${ROUTES.projects}/${projectId}/surveys/${surveyId}`,
    projectSurveyAuditors: (projectId: string, surveyId: string) => `${ROUTES.projects}/${projectId}/surveys/${surveyId}/auditors`,
    projectSurveyAuditor: (projectId: string, surveyId: string, auditorId: string) =>
      `${ROUTES.projects}/${projectId}/surveys/${surveyId}/auditors/${auditorId}`,
    projectSurveyTestInvite: (projectId: string, surveyId: string) => `${ROUTES.projects}/${projectId}/surveys/${surveyId}/invites/test`,
    projectSurveyAuditorInvite: (projectId: string, surveyId: string, auditorId: string) =>
      `${ROUTES.projects}/${projectId}/surveys/${surveyId}/auditors/${auditorId}/invite`,
  },
  surveys: {
    surveys: `${ROUTES.surveys}`,
    survey: (surveyId: string) => `${ROUTES.surveys}/${surveyId}`,
    surveyBuilder: (surveyId: string) => `${ROUTES.surveys}/${surveyId}/builder`,
    surveyProjects: (surveyId: string) => `${ROUTES.surveys}/${surveyId}/projects`,
    surveyApplyTemplate: (surveyId: string) => `${ROUTES.surveys}/${surveyId}/apply-template`,
    surveyQuestion: (surveyId: string, questionId: string) => `${ROUTES.surveys}/${surveyId}/questions/${questionId}`,
    surveyPages: (surveyId: string) => `${ROUTES.surveys}/${surveyId}/pages`,
    surveyPage: (surveyId: string, pageId: string) => `${ROUTES.surveys}/${surveyId}/pages/${pageId}`,
    surveyQuestions: (surveyId: string) => `${ROUTES.surveys}/${surveyId}/questions`,
    surveyQuestionOption: (surveyId: string, questionId: string, optionId: string) =>
      `${ROUTES.surveys}/${surveyId}/questions/${questionId}/options/${optionId}`,
    surveyReorder: (surveyId: string) => `${ROUTES.surveys}/${surveyId}/reorder`,
    surveyPublish: (surveyId: string) => `${ROUTES.surveys}/${surveyId}/publish`,
    surveyModeration: (surveyId: string) => `${ROUTES.surveys}/${surveyId}/moderation`,
    surveyArchive: (surveyId: string) => `${ROUTES.surveys}/${surveyId}/archive`,
    surveyUnarchive: (surveyId: string) => `${ROUTES.surveys}/${surveyId}/unarchive`,
    surveySimulate: (surveyId: string) => `${ROUTES.surveys}/${surveyId}/simulate`,
    surveyAnalytics: (surveyId: string) => `${ROUTES.surveys}/${surveyId}/analytics`,
  },
  auditors: {
    auditors: `${ROUTES.auditors}`,
    export: `${ROUTES.auditors}/export`,
    auditor: (auditorId: string) => `${ROUTES.auditors}/${auditorId}`,
    import: `${ROUTES.auditors}/import`,
    password: (auditorId: string) => `${ROUTES.auditors}/${auditorId}/password`,
  },
  public: {
    pa: (token: string) => `public/pa/${token}`,
    paOptions: (token: string) => `public/pa/${token}/options`,
    paDraft: (token: string) => `public/pa/${token}/draft`,
    paSubmit: (token: string) => `public/pa/${token}/submit`,
  },
  priceMonitoring: {
    stats: `${ROUTES.priceMonitoring}/stats`,
    attempts: `${ROUTES.priceMonitoring}/attempts`,
    attempt: (attemptId: string) => `${ROUTES.priceMonitoring}/attempts/${attemptId}`,
  },
  auditorAuth: {
    login: `${ROUTES.auditorAuth}/login`,
    refresh: `${ROUTES.auditorAuth}/refresh`,
    logout: `${ROUTES.auditorAuth}/logout`,
  },
  auditor: {
    me: `${ROUTES.auditor}/me`,
    assignments: `${ROUTES.auditor}/assignments`,
    assignmentStatus: (projectId: string, surveyId: string) => `${ROUTES.auditor}/assignments/${projectId}/${surveyId}/status`,
  },
} as const